### core project imports...
import reflex as rx

### configuration imports...
from rxconfig import config

### page route imports...
from cyber_industrial.page.index import index

### application instantiation...
app = rx.App()

### application page routing...
app.add_page(index)
